spring.application.name=api-gateway
server.port=8080

services.necesidades.url=http://host.docker.internal:8083
services.donaciones.url=http://host.docker.internal:8082
services.logistica.url=http://host.docker.internal:8084

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs