spring.application.name=api-gateway
server.port=8080

services.necesidades.url=http://localhost:8083
services.donaciones.url=http://localhost:8082
services.logistica.url=http://localhost:8084

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs